const {chromium}=require('playwright');const assert=require('node:assert/strict');const fs=require('node:fs');const path=require('node:path');
const base=process.env.BASE_URL||'http://127.0.0.1:4180/apps/web/';const out=path.join(__dirname,'artifacts');const checks=[];
const check=(name)=>{checks.push(name);console.log('PASS',name)};
const screenshot=async(p,name)=>{await p.locator('#toast').evaluate(e=>e.hidden=true);await p.screenshot({path:path.join(out,name+'.png'),fullPage:!(await p.locator('dialog[open]').count())});};
async function register(p,name='hayashi'){await p.goto(base+'#register');await p.locator('#registerName').fill(name==='hayashi'?'林':name);await p.locator('#authName').fill(name);await p.locator('#authPassword').fill('test-pass-2026');await p.locator('#confirmPassword').fill('test-pass-2026');await p.locator('#authSubmit').click();await p.waitForURL('**/#login');}
async function login(p,name='hayashi'){await p.locator('#authName').fill(name);await p.locator('#authPassword').fill('test-pass-2026');await p.locator('#authSubmit').click();await p.locator('.sidebar').waitFor();}
async function select(p,word){await p.locator('#articleEditor').focus();await p.evaluate(word=>{const root=document.querySelector('#articleEditor');const all=root.textContent;const start=all.indexOf(word);if(start<0)throw Error('word missing');const nodes=[];let offset=0;const walker=document.createTreeWalker(root,NodeFilter.SHOW_TEXT);let n;while(n=walker.nextNode()){nodes.push({n,start:offset,end:offset+n.length});offset+=n.length;}const point=i=>{const p=nodes.find(n=>i<=n.end);return [p.n,i-p.start]};const r=document.createRange();r.setStart(...point(start));r.setEnd(...point(start+word.length));getSelection().removeAllRanges();getSelection().addRange(r);root.dispatchEvent(new MouseEvent('mouseup',{bubbles:true}));},word);await p.locator('#editSelected').click();await p.locator('#readingDialog').waitFor();}
async function save(p,reading){await p.locator('#readingInput').fill(reading);await p.locator('#saveRuleButton').click();await p.locator('#readingDialog').waitFor({state:'hidden'});}
(async()=>{fs.mkdirSync(out,{recursive:true});const browser=await chromium.launch({headless:true});const errors=[];try{
const context=await browser.newContext({viewport:{width:1440,height:1000},reducedMotion:'reduce'});const p=await context.newPage();p.on('pageerror',e=>errors.push(e.message));
await p.goto(base+'#rules');assert(await p.locator('#authView').isVisible());check('未登录保护路由');await screenshot(p,'login');
await p.locator('a[href="#register"]').click();await screenshot(p,'register');await p.setViewportSize({width:390,height:844});await screenshot(p,'mobile-register');await p.goto(base+'#login');await screenshot(p,'mobile-login');await p.setViewportSize({width:1440,height:1000});await register(p);await p.locator('#authPassword').fill('wrong-password');await p.locator('#authSubmit').click();await p.locator('#authError').waitFor();assert.match(await p.locator('#authError').innerText(),/不正确/);check('本机创建账户与错误密码拒绝');
await login(p); // protected return route may be rules
await p.locator('[data-view="workbench"]').first().click();
assert(await p.locator('#generateButton').isDisabled());assert(await p.locator('#audioResult').isHidden());check('无日文音色不生成虚假结果');await p.locator('#articleEditor').focus();await p.locator('#articleEditor').press('Control+Home');await p.locator('#articleEditor').press('Shift+ArrowRight');await p.locator('#articleEditor').press('Shift+ArrowRight');await p.locator('#editSelectionButton').click();assert.equal(await p.locator('#selectedWord').inputValue(),'朝の');await p.locator('#cancelRuleButton').click();check('键盘选词与浮动入口');
const original=await p.locator('#articleEditor').textContent();await select(p,'日本橋');await screenshot(p,'reading-editor');await save(p,'にほんばし');assert.equal(await p.locator('#articleEditor').textContent(),original);assert.equal(await p.locator('#articleEditor mark').count(),2);check('正文真实选区保存、原字保留与当前同词复用');
await screenshot(p,'workbench');await p.reload();assert.equal(await p.locator('#articleEditor mark').count(),2);check('刷新后个人规则持久化');
await p.locator('#newArticleButton').click();await p.locator('#loadSampleTwo').click();await p.locator('#applyArticle').click();assert.equal(await p.locator('#articleEditor mark').count(),2);check('新文章自动复用个人读法');
await select(p,'日本橋');await p.locator('#readingInput').fill('にっぽんばし');
await p.evaluate(()=>{window.originalSet=Storage.prototype.setItem;Storage.prototype.setItem=function(k,v){if(k==='yomi-web-v1')throw new DOMException('full','QuotaExceededError');return window.originalSet.call(this,k,v);}});await p.locator('#saveRuleButton').click();await p.locator('#saveError').waitFor();assert.equal(await p.locator('#readingInput').inputValue(),'にっぽんばし');assert.match(await p.locator('#articleEditor mark').first().getAttribute('title'),/にほんばし/);check('真实存储写入失败保留表单与旧规则');await screenshot(p,'save-error');await p.evaluate(()=>Storage.prototype.setItem=window.originalSet);await p.locator('#cancelRuleButton').click();
await p.locator('[data-view="rules"]').first().click();await screenshot(p,'rules');await p.locator('#ruleSearch').fill('不存在');assert(await p.locator('#rulesEmpty').isVisible());await p.locator('#ruleSearch').fill('にほん');assert.equal(await p.locator('#rulesTableBody tr').count(),1);await p.locator('#ruleSearch').fill('');check('规则列表查询与无结果');
await p.locator('#addRuleButton').click();await p.locator('#modalWord').fill('京都');await p.locator('#modalReading').fill('きょうと');await p.locator('#modalSave').click();await p.locator('#ruleDialog').waitFor({state:'hidden'});await p.locator('[data-action="edit"][aria-label="编辑 京都"]').click();await p.locator('#modalReading').fill('キョウト');await p.locator('#modalSave').click();await p.locator('#ruleDialog').waitFor({state:'hidden'});check('独立页面新增编辑个人规则');
const p2=await context.newPage();await p2.goto(base);await login(p2);await p2.locator('[data-view="rules"]').first().click();await p.locator('[data-action="edit"][aria-label="编辑 京都"]').click();await p2.locator('[data-action="edit"][aria-label="编辑 京都"]').click();await p2.locator('#modalReading').fill('きょーと');await p2.locator('#modalSave').click();await p2.locator('#ruleDialog').waitFor({state:'hidden'});await p.locator('#modalReading').fill('きょうと');await p.locator('#modalSave').click();await p.locator('#modalRuleError').waitFor();assert.match(await p.locator('#modalRuleError').innerText(),/另一窗口/);await p.locator('#cancelModalRule').click();await p2.close();check('多窗口旧版本冲突拒绝覆盖');
await p.locator('[data-action="delete"][aria-label="删除 日本橋"]').click();await p.evaluate(()=>{window.originalSet=Storage.prototype.setItem;Storage.prototype.setItem=function(k,v){if(k==='yomi-web-v1')throw Error('full');return window.originalSet.call(this,k,v);}});await p.locator('#confirmDelete').click();await p.locator('#deleteError').waitFor();assert.equal(await p.locator('#rulesTableBody tr').count(),2);await p.evaluate(()=>Storage.prototype.setItem=window.originalSet);await p.locator('#confirmDelete').click();await p.locator('#confirmDialog').waitFor({state:'hidden'});await p.locator('[data-view="workbench"]').first().click();assert.equal(await p.locator('#articleEditor mark').count(),1);check('删除失败保持状态、重试后移除规则投影');
await p.locator('#articleEditor').fill('京都\n日本橋😀\n\nカタカナとひらがな。');assert.equal(await p.locator('#articleEditor').textContent(),'京都\n日本橋😀\n\nカタカナとひらがな。');await p.locator('#articleEditor').press('Control+End');await p.locator('#articleEditor').press('Enter');await p.locator('#articleEditor').pressSequentially('京都');assert((await p.locator('#articleEditor').textContent()).endsWith('\n京都'));await select(p,'日本橋');await save(p,'にほんばし');check('多行、emoji、换行后输入与再次选词');
await p.locator('#articleEditor').evaluate(el=>{el.dispatchEvent(new CompositionEvent('compositionstart',{bubbles:true}));el.textContent='変換中の京都\n日本橋';el.dispatchEvent(new InputEvent('input',{bubbles:true,isComposing:true,inputType:'insertCompositionText',data:'京都'}));});assert.equal(await p.locator('#articleEditor mark').count(),0);await p.locator('#articleEditor').evaluate(el=>el.dispatchEvent(new CompositionEvent('compositionend',{bubbles:true,data:'京都'})));assert.equal(await p.locator('#articleEditor mark').count(),2);check('IME 合成期间不重写 DOM，提交后重算标记');
await p.locator('#articleEditor').fill('日'.repeat(10001));assert(await p.locator('#generateButton').isDisabled());assert.match(await p.locator('#inputNotice').innerText(),/超过/);await p.locator('#articleEditor').fill('');assert(await p.locator('#generateButton').isDisabled());check('长正文与空正文禁用');await p.locator('#newArticleButton').click();await p.locator('#loadSampleOne').click();await p.locator('#applyArticle').click();
await p.locator('[data-view="account"]').first().click();await p.locator('#displayName').fill('林の書斎');await p.locator('#profileSave').click();await p.waitForFunction(()=>document.querySelector('#profileName').textContent==='林の書斎');await screenshot(p,'account');check('账户资料保存');
await p.setViewportSize({width:390,height:844});for(const view of ['workbench','rules','account']){await p.locator(`[data-view="${view}"]`).first().click();assert(await p.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1),view+' mobile overflow');await screenshot(p,'mobile-'+view);}await p.locator('[data-view="workbench"]').first().click();await select(p,'日本橋');assert(await p.locator('#readingInput').evaluate(e=>document.activeElement===e));await screenshot(p,'mobile-reading');await p.keyboard.press('Escape');assert(await p.locator('#readingDialog').isHidden());check('390px 所有页面无横向溢出、弹层聚焦与 Escape');await p.setViewportSize({width:320,height:740});for(const view of ['workbench','rules','account']){await p.locator(`[data-view="${view}"]`).first().click();assert(await p.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1),view+' 320px overflow');}await p.setViewportSize({width:390,height:844});await p.locator('[data-view="workbench"]').first().click();check('320px 最窄布局覆盖');
await p.evaluate(()=>{const s=JSON.parse(sessionStorage.getItem('yomi-session-v1'));s.until=0;sessionStorage.setItem('yomi-session-v1',JSON.stringify(s));window.dispatchEvent(new Event('focus'));});await p.locator('#authView').waitFor();assert.match(await p.locator('#sessionNotice').innerText(),/失效/);await screenshot(p,'session-expired');await login(p);assert((await p.locator('#articleEditor').textContent()).includes('日本橋'));check('会话失效与同账户重新登录保留正文');
await p.locator('[data-view="account"]').first().click();await p.locator('#logoutButton').click();await register(p,'second');await login(p,'second');assert.equal(await p.locator('#navRuleCount').textContent(),'0');assert.equal(await p.locator('#articleEditor').textContent(),'');check('退出、另一账户隔离及清理正文');
const closed=await browser.newContext();await closed.route('**/src/config.js',r=>r.fulfill({contentType:'text/javascript',body:'export const config={registrationOpen:false,sessionMs:28800000,maxText:10000};'}));const cp=await closed.newPage();await cp.goto(base+'#register');assert(await cp.locator('#authForm').isHidden());assert.match(await cp.locator('#authTitle').innerText(),/暂未开放/);await screenshot(cp,'registration-closed');check('注册关闭配置与直达路由');await closed.close();
// Test-only speech adapter uses real PCM WAV bytes and native Audio events. It is not Japanese synthesis.
const audioContext=await browser.newContext({viewport:{width:1440,height:1000}});const source=fs.readFileSync(path.join(__dirname,'../src/services.js'),'utf8');const testSpeech=`export const speechService={async voices(){return [{id:'fixture',name:'QA PCM audio'}]},start(snapshot,h){this.stop();if(sessionStorage.getItem('qa-audio-fail')){h.onError(Error('音频启动失败，请重试。'));return;}const a=new Audio('./qa/tone.wav');this.audio=a;window.qaSnapshot=snapshot;a.onplaying=()=>h.onStart({kind:'fixture',downloadUrl:null});a.onended=h.onEnd;a.onerror=()=>h.onError(Error('fixture playback failed'));a.play().catch(h.onError);},stop(){if(this.audio){this.audio.onplaying=null;this.audio.onended=null;this.audio.pause();}},pause(){this.audio?.pause()},resume(){this.audio?.play()}};`;
await audioContext.route('**/src/services.js',r=>r.fulfill({contentType:'text/javascript',body:source.slice(0,source.indexOf('export const speechService='))+testSpeech}));const ap=await audioContext.newPage();ap.on('pageerror',e=>errors.push(e.message));await register(ap);await login(ap);await select(ap,'日本橋');await save(ap,'にほんばし');await ap.locator('#generateButton').click();await ap.locator('#audioResult').waitFor();assert((await ap.evaluate(()=>window.qaSnapshot.text)).includes('にほんばし'));assert(!(await ap.evaluate(()=>window.qaSnapshot.text)).includes('日本橋'));await ap.locator('#playButton').click();assert.match(await ap.locator('#playState').innerText(),/暂停/);await ap.locator('#playButton').click();await ap.locator('#stopButton').click();check('真实 WAV 播放事件驱动结果，读法快照、暂停继续与停止');
await select(ap,'日本橋');await save(ap,'にっぽんばし');assert(await ap.locator('#staleBanner').isVisible());await ap.evaluate(()=>sessionStorage.setItem('qa-audio-fail','1'));await ap.locator('#generateButton').click();await ap.locator('#generationError').waitFor();assert(await ap.locator('#staleBanner').isVisible());await ap.evaluate(()=>sessionStorage.removeItem('qa-audio-fail'));await ap.locator('#generateButton').click();await ap.waitForFunction(()=>document.querySelector('#staleBanner').hidden);await ap.locator('#stopButton').click();assert(await ap.locator('#downloadButton').isDisabled());check('规则变更旧音频过期、失败保留旧结果、重新生成与不可伪下载');
await ap.locator('#generateButton').click();await ap.locator('#speedRange').fill('1.5');await ap.waitForFunction(()=>!document.querySelector('#audioResult').hidden);assert(await ap.locator('#staleBanner').isVisible());check('生成提交快照与参数变更过期');await audioContext.close();
const model=await p.evaluate(async()=>{const {applyRules}=await import('./src/model.js');return applyRules('日本橋日本橋A',[{word:'日本',reading:'にほん'},{word:'日本橋',reading:'にほんばし'},{word:'A',reading:'日本橋'}]);});assert.equal(model.output,'にほんばしにほんばし日本橋');check('最左最长字面匹配与单轮非递归');
assert.deepEqual(errors,[]);check('所有运行页面无未捕获异常');fs.writeFileSync(path.join(out,'results.json'),JSON.stringify({date:new Date().toISOString(),checks,speechNote:'Native Audio with test-only PCM WAV fixture; not Japanese voice or Gateway acceptance',errors},null,2));
}finally{await browser.close();}})().catch(e=>{console.error(e);process.exit(1)});
