const {chromium}=require('playwright');const assert=require('node:assert/strict');const fs=require('node:fs');const path=require('node:path');const {randomUUID}=require('node:crypto');
const base=process.env.BASE_URL||'http://127.0.0.1:4181/';const out=path.join(__dirname,'integration-artifacts');
async function select(p,word){await p.locator('#articleEditor').focus();await p.evaluate(word=>{const root=document.querySelector('#articleEditor'),w=document.createTreeWalker(root,NodeFilter.SHOW_TEXT),nodes=[];let n,c=0;while(n=w.nextNode()){nodes.push({n,start:c,end:c+n.length});c+=n.length;}const start=root.textContent.indexOf(word);const point=i=>{const n=nodes.find(n=>i<=n.end);return [n.n,i-n.start]};const r=document.createRange();r.setStart(...point(start));r.setEnd(...point(start+word.length));getSelection().removeAllRanges();getSelection().addRange(r);root.dispatchEvent(new MouseEvent('mouseup',{bubbles:true}));},word);await p.locator('#editSelected').click();await p.locator('#readingDialog').waitFor();}
(async()=>{fs.mkdirSync(out,{recursive:true});const browser=await chromium.launch({headless:true});const context=await browser.newContext({viewport:{width:1440,height:1000}});const p=await context.newPage();const errors=[],responses=[];p.on('pageerror',e=>errors.push(e.message));p.on('response',r=>{if(r.url().includes('/v1/'))responses.push({path:new URL(r.url()).pathname,status:r.status()});});
try{const login='web-'+randomUUID().slice(0,12),password=randomUUID()+'-A1';await p.goto(base+'#/register');await p.locator('#registerName').waitFor();await p.locator('#registerName').fill('前端联调');await p.locator('#authName').fill(login);await p.locator('#authPassword').fill(password);await p.locator('#confirmPassword').fill(password);await p.locator('#authSubmit').click();await p.waitForURL('**/#/login');assert(!await p.locator('.sidebar').count());await p.locator('#authPassword').fill(password);await p.locator('#authSubmit').click();await p.locator('.sidebar').waitFor();await p.locator('[data-view="account"]').click();await p.locator('#displayName').fill('前端联调完成');await p.locator('#profileSave').click();await p.waitForFunction(()=>document.querySelector('#profileName').textContent==='前端联调完成');await p.reload();await p.waitForFunction(()=>document.querySelector('#profileName')?.textContent==='前端联调完成');await p.screenshot({path:path.join(out,'account.png'),fullPage:true});await p.locator('[data-view="workbench"]').click();assert(await p.locator('#generateButton').isDisabled());await p.screenshot({path:path.join(out,'workbench.png'),fullPage:true});
await p.locator('#articleEditor').waitFor();
await select(p,'日本橋');await p.locator('#readingInput').fill('にほんばし');await p.locator('#saveRuleButton').click();await p.locator('#readingDialog').waitFor({state:'hidden'});assert.equal(await p.locator('#articleEditor mark').count(),2);
await p.locator('#newArticleButton').click();await p.locator('#loadSampleTwo').click();await p.locator('#applyArticle').click();assert.equal(await p.locator('#articleEditor mark').count(),2);await p.reload();await p.locator('#articleEditor mark').first().waitFor();assert.equal(await p.locator('#articleEditor mark').count(),2);
let page=await (await context.request.get(base+'v1/vocabulary?limit=500&offset=0')).json();assert.equal(page.items.length,1);const first=page.items[0];
const token=await (await context.request.get(base+'v1/auth/csrf')).json();const headers={'Origin':new URL(base).origin,'X-CSRF-Token':token.csrfToken};
await select(p,'日本橋');const changed=await context.request.patch(base+'v1/vocabulary/'+first.id,{headers,data:{text:first.text,reading:'ニホンバシ',expectedRevision:first.revision}});assert.equal(changed.status(),200);await p.locator('#readingInput').fill('にっぽんばし');await p.locator('#saveRuleButton').click();await p.locator('#saveError').waitFor();assert.match(await p.locator('#saveError').innerText(),/另一窗口/);assert.equal(await p.locator('#readingInput').inputValue(),'にっぽんばし');await p.locator('#cancelRuleButton').click();await p.waitForFunction(()=>document.querySelector('#articleEditor mark').title.includes('ニホンバシ'));
await p.locator('[data-view="rules"]').click();await p.locator('#addRuleButton').click();await p.locator('#modalWord').fill('京都');await p.locator('#modalReading').fill('きょうと');await p.locator('#modalSave').click();await p.locator('#ruleDialog').waitFor({state:'hidden'});await p.locator('#ruleSearch').fill('きょう');assert.equal(await p.locator('#rulesTableBody tr').count(),1);await p.locator('#ruleSearch').fill('');
await p.screenshot({path:path.join(out,'rules.png'),fullPage:true});await p.locator('[data-view="workbench"]').click();await select(p,'日本橋');await p.screenshot({path:path.join(out,'reading.png')});await p.locator('#cancelRuleButton').click();await p.setViewportSize({width:390,height:844});await p.screenshot({path:path.join(out,'mobile-workbench.png'),fullPage:true});await p.setViewportSize({width:1440,height:1000});
const csrfFailure=await context.request.post(base+'v1/vocabulary',{headers:{Origin:new URL(base).origin,'X-CSRF-Token':'invalid'},data:{text:'誤り',reading:'あやまり'}});assert.equal(csrfFailure.status(),403);
const tts=await context.request.post(base+'v1/audio/speech',{headers,data:{input:'日本橋を歩く。',voice:'not-configured',language:'ja-JP',inputType:'text',format:'mp3',speed:1}});assert.equal(tts.status(),503);assert((tts.headers()['content-type']||'').includes('application/json'));
await p.locator('[data-view="rules"]').click();for(const word of ['京都','日本橋']){await p.locator('[aria-label="删除 '+word+'"]').click();await p.locator('#confirmDelete').click();await p.locator('#confirmDialog').waitFor({state:'hidden'});}await p.locator('#rulesEmpty').waitFor();page=await (await context.request.get(base+'v1/vocabulary?limit=500&offset=0')).json();assert.equal(page.total,0);assert(page.internalVersion>=5);

const cookies=await context.cookies();const session=cookies.find(c=>c.name==='wb_session');assert(session&&session.httpOnly&&session.sameSite==='Lax');await p.locator('[data-view="account"]').click();await p.locator('#logoutButton').click();await p.locator('#authView').waitFor();const me=await context.request.get(base+'v1/auth/me');assert.equal(me.status(),401);assert(responses.filter(r=>r.path.endsWith('/csrf')&&r.status===200).length>=3);assert.deepEqual(errors,[]);fs.writeFileSync(path.join(out,'full-results.json'),JSON.stringify({date:new Date().toISOString(),origin:base,checks:['真实PG账户注册且不自动登录','Cookie登录与资料PATCH','刷新后会话和显示名称保留','wb_session HttpOnly SameSite=Lax','登录/退出CSRF轮换','退出后me401','无音色禁用生成','真实个人规则POST及当前同词标记','新文章与刷新持久复用','真实PATCH并发409保留表单与旧服务状态','个人规则新增查询及DELETE204版本更新','无效CSRF真实403','未配置语音真实503 JSON'],responses,errors},null,2));console.log('PASS real authentication integration',responses.filter(r=>r.path.includes('/auth/')));
}finally{await browser.close();}})().catch(e=>{console.error(e);process.exit(1)});
