const {chromium}=require('playwright');const assert=require('node:assert/strict');const fs=require('node:fs');const path=require('node:path');const {randomUUID}=require('node:crypto');
require('./contract-check.cjs');
const contractMetadata=JSON.parse(fs.readFileSync(path.join(__dirname,'../src/api/contract.json'),'utf8'));
const base=process.env.BASE_URL||'http://127.0.0.1:4181/';const out=path.join(__dirname,'react-artifacts');const audio=fs.readFileSync(path.join(__dirname,'tone.mp3'));const checks=[];
function ok(s){checks.push(s);console.log('PASS',s)}
async function screenshot(p,name){await p.evaluate(()=>new Promise(resolve=>requestAnimationFrame(()=>requestAnimationFrame(resolve))));await p.locator('#toast').evaluateAll(items=>items.forEach(e=>e.style.visibility='hidden'));await p.screenshot({path:path.join(out,name+'.png'),fullPage:!(await p.locator('[role="dialog"]').count())});}
async function fixture(context){const state={accounts:[],current:null,registration:true,voices:false,fail:null,audioFail:false,badAudio:false,delayAudio:0,csrf:'token-0',version:0,requests:[],csrfReads:0};
await context.route('**/v1/**',async route=>{const req=route.request(),url=new URL(req.url()),endpoint=url.pathname,method=req.method(),body=req.postDataJSON();state.requests.push({method,path:endpoint,body});const requestId=randomUUID();const headers={'X-Request-Id':requestId,'Cache-Control':'no-store'};
const send=(data,status=200,extra={})=>route.fulfill({status,headers:{...headers,'Content-Type':'application/json',...extra},body:JSON.stringify(data)});const error=(status,code)=>send({code,message:code,requestId},status);
if(method!=='GET'){assert.equal(req.headers()['x-csrf-token'],state.csrf,'CSRF mismatch');assert.equal(req.headers().origin,new URL(base).origin,'Origin mismatch');}
if(endpoint==='/v1/config')return send({registrationEnabled:state.registration,language:'ja-JP',maxVocabularyEntries:500,maxInputCodePoints:10000,maxInputBytes:49152,maxArticles:100});
if(endpoint==='/v1/auth/csrf'){state.csrfReads++;return send({csrfToken:state.csrf,expiresAt:new Date(Date.now()+3600000).toISOString()});}
if(endpoint==='/v1/auth/register'){assert.deepEqual(Object.keys(body).sort(),['displayName','login','password']);if(!state.registration)return error(403,'REGISTRATION_DISABLED');if(state.accounts.some(a=>a.login===body.login))return error(409,'ALREADY_EXISTS');state.accounts.push({id:randomUUID(),login:body.login,displayName:body.displayName,status:'active',password:body.password,rules:[],articles:[],version:0});const {password,rules,version,...a}=state.accounts.at(-1);return send(a,201);}
if(endpoint==='/v1/auth/login'){const a=state.accounts.find(a=>a.login===body.login&&a.password===body.password);if(!a)return error(401,'UNAUTHENTICATED');state.current=a;state.csrf=randomUUID();const {password,rules,version,...publicAccount}=a;return send(publicAccount);}
if(endpoint==='/v1/auth/logout'){state.current=null;state.csrf=randomUUID();return route.fulfill({status:204,headers});}
if(!state.current)return error(401,'UNAUTHENTICATED');const a=state.current;
if(state.fail&&state.fail===method+':'+endpoint){state.fail=null;return error(503,'DEPENDENCY_UNAVAILABLE');}
if(endpoint==='/v1/auth/me'){if(method==='PATCH')a.displayName=body.displayName;const {password,rules,version,...account}=a;return send(account);}
if(endpoint==='/v1/articles'&&method==='GET'){const rows=a.articles;return send({items:rows,total:rows.length,offset:0,limit:20});}
if(endpoint==='/v1/articles'&&method==='POST'){const entry={id:randomUUID(),...body,revision:1,contentRevision:1,createdAt:new Date().toISOString(),updatedAt:new Date().toISOString(),currentRuleVersion:a.version,audio:null,audioStale:false};a.articles.unshift(entry);return send(entry,201);}
if(endpoint.startsWith('/v1/articles/')){const entry=a.articles.find(x=>x.id===endpoint.split('/').at(-1));if(!entry)return error(404,'NOT_FOUND');if(method==='GET')return send(entry);if(body.expectedRevision!==entry.revision)return error(409,'REVISION_CONFLICT');Object.assign(entry,body,{revision:entry.revision+1,contentRevision:entry.contentRevision+(entry.text!==body.text?1:0)});return send(entry);}
if(endpoint==='/v1/voices')return send({items:state.voices?[{id:'qa-ja',name:'QA 契约测试音色',language:'ja-JP',provider:'azure-speech'}]:[]});
if(endpoint==='/v1/vocabulary'&&method==='GET'){assert.equal(url.searchParams.get('limit'),'500');assert.equal(url.searchParams.get('q'),null);return send({items:a.rules,total:a.rules.length,offset:0,limit:500,internalVersion:a.version});}
if(endpoint==='/v1/vocabulary'&&method==='POST'){assert.deepEqual(Object.keys(body).sort(),['reading','text']);if(a.rules.some(r=>r.text===body.text.normalize('NFC')))return error(409,'ALREADY_EXISTS');const entry={id:randomUUID(),text:body.text.normalize('NFC'),reading:body.reading.normalize('NFC'),revision:1,createdAt:new Date().toISOString(),updatedAt:new Date().toISOString()};a.rules.push(entry);a.version++;return send({entry,internalVersion:a.version},201);}
if(endpoint.startsWith('/v1/vocabulary/')){const id=endpoint.split('/').at(-1),entry=a.rules.find(r=>r.id===id);if(!entry)return error(404,'NOT_FOUND');const expected=method==='DELETE'?Number(url.searchParams.get('expectedRevision')):body.expectedRevision;if(expected!==entry.revision)return error(409,'REVISION_CONFLICT');if(method==='DELETE'){a.rules=a.rules.filter(r=>r.id!==id);a.version++;return route.fulfill({status:204,headers:{...headers,'X-Pronunciation-Version':String(a.version)}});}assert.deepEqual(Object.keys(body).sort(),['expectedRevision','reading','text']);if(a.rules.some(r=>r.id!==id&&r.text===body.text))return error(409,'ALREADY_EXISTS');Object.assign(entry,{text:body.text.normalize('NFC'),reading:body.reading.normalize('NFC'),revision:entry.revision+1});a.version++;return send({entry,internalVersion:a.version});}
if(endpoint.startsWith('/v1/audio/')){if(endpoint.endsWith('speech'))assert.deepEqual(Object.keys(body).sort(),['format','input','inputType','language','speed','voice']);else assert.deepEqual(Object.keys(body).sort(),['reading','speed','text','voice']);if(state.audioFail)return error(503,'TTS_UNAVAILABLE');const version=a.version;if(state.delayAudio)await new Promise(r=>setTimeout(r,state.delayAudio));return route.fulfill({status:200,headers:{...headers,'Content-Type':state.badAudio?'application/json':'audio/mpeg','Content-Length':String(audio.length),'Content-Disposition':'inline; filename="contract-test.mp3"','X-Pronunciation-Version':String(version)},body:audio});}
throw Error('Uncovered request '+method+' '+endpoint);
});return state;}
async function register(p,name='reader'){await p.goto(base+'#/register');await p.locator('#registerName').fill('林');await p.locator('#authName').fill(name);await p.locator('#authPassword').fill('Eight123');await p.locator('#confirmPassword').fill('Eight123');await p.locator('#authSubmit').click();await p.waitForURL('**/#/login');}
async function openWorkbench(p){await p.locator('[data-view="workbench"]').click();if(await p.locator('#articleEditor').count())return;await p.locator('.article-title').first().click();await p.locator('#articleEditor').waitFor();}
async function createArticle(p,title,text){await p.locator('#newArticleButton').click();await p.waitForFunction(()=>location.hash==='#/articles/new'||document.querySelector('#unsavedDialog'));if(await p.locator('#unsavedDialog').count())await p.getByRole('button',{name:'放弃更改',exact:true}).click();await p.waitForURL('**/#/articles/new');await p.waitForFunction(()=>document.querySelector('#articleSaveStatus')?.textContent==='尚未创建');await p.locator('#articleTitle').fill(title);await p.locator('#articleEditor').fill(text);await p.locator('#saveArticle').click();await p.waitForFunction(()=>document.querySelector('#articleSaveStatus')?.textContent==='已保存到我的文章');}
async function login(p,name='reader'){await p.locator('#authName').fill(name);await p.locator('#authPassword').fill('Eight123');await p.locator('#authSubmit').click();await p.locator('.sidebar').waitFor();if(await p.locator('#articleEditor').count())return;await p.locator('[data-view="articles"]').click();await p.locator('#articlesView').waitFor();if(await p.locator('.article-title').count())await p.locator('.article-title').first().click();else await createArticle(p,'京都的早晨',name==='reader'?'京都の朝。日本橋を歩く。日本橋の空。':'');await p.locator('#articleEditor').waitFor();}
async function select(p,word){await p.locator('#articleEditor').focus();await p.evaluate(word=>{const root=document.querySelector('#articleEditor'),walker=document.createTreeWalker(root,NodeFilter.SHOW_TEXT),nodes=[];let n,c=0;while(n=walker.nextNode()){nodes.push({n,start:c,end:c+n.length});c+=n.length;}const i=root.textContent.indexOf(word);if(i<0)throw Error('word missing');const point=i=>{const n=nodes.find(n=>i<=n.end);return[n.n,i-n.start]};const r=document.createRange();r.setStart(...point(i));r.setEnd(...point(i+word.length));getSelection().removeAllRanges();getSelection().addRange(r);root.dispatchEvent(new MouseEvent('mouseup',{bubbles:true}));},word);await p.locator('#editSelected').click();await p.locator('#readingDialog').waitFor();}
async function save(p,reading){await p.locator('#readingInput').fill(reading);await p.locator('#saveRuleButton').click();await p.locator('#readingDialog').waitFor({state:'hidden'});}
(async()=>{fs.mkdirSync(out,{recursive:true});const browser=await chromium.launch({headless:true});const errors=[];try{const context=await browser.newContext({viewport:{width:1440,height:1000},reducedMotion:'reduce'});const state=await fixture(context);const p=await context.newPage();p.on('pageerror',e=>errors.push(e.message));await p.goto(base+'#/rules');await p.locator('#authSubmit').waitFor();assert(await p.locator('#authView').isVisible());await screenshot(p,'login');ok('React Router未登录保护及页面启动');
await p.getByRole('link',{name:'还没有账户？创建账户 →'}).click();await p.locator('#registerName').fill('林');await p.locator('#authName').fill('r');await p.locator('#authPassword').fill('1234567');await p.locator('#confirmPassword').fill('different');await p.locator('#authSubmit').click();assert.match(await p.locator('#authError').innerText(),/8 位/);assert(!state.requests.some(r=>r.path.endsWith('/register')));ok('RHF/Zod阻止不符合契约的注册字段');await register(p);assert.equal(state.current,null);await p.locator('#authPassword').fill('wrong-password');await p.locator('#authSubmit').click();await p.locator('#authError').waitFor();assert.match(await p.locator('#authError').innerText(),/不正确/);await login(p);assert(state.csrfReads>=2);ok('契约注册不自动登录、错误凭据与CSRF轮换');
assert(await p.locator('#generateButton').isDisabled());assert.equal(await p.locator('#audioResult').count(),0);await screenshot(p,'workbench-no-voice');ok('真实服务入口不兜底本地音色或假音频');
const original=await p.locator('#articleEditor').textContent();await select(p,'日本橋');await screenshot(p,'reading-editor');await save(p,'にほんばし');assert.equal(await p.locator('#articleEditor').textContent(),original);assert.equal(await p.locator('#articleEditor mark').count(),2);assert.equal(state.current.rules.length,1);ok('正文选词、HTTP保存确认、原字和同词投影');
await createArticle(p,'旅途的记忆','旅の日本橋。日本橋の記憶。');assert.equal(await p.locator('#articleEditor mark').count(),2);await p.reload();await p.locator('#articleEditor mark').first().waitFor();assert.equal(await p.locator('#articleEditor mark').count(),2);ok('跨文章与刷新使用服务端个人规则');
await select(p,'日本橋');await p.locator('#readingInput').fill('にっぽんばし');state.fail='PATCH:/v1/vocabulary/'+state.current.rules[0].id;await p.locator('#saveRuleButton').click();await p.locator('#saveError').waitFor();assert.equal(state.current.rules[0].reading,'にほんばし');assert.equal(await p.locator('#readingInput').inputValue(),'にっぽんばし');await p.locator('#cancelRuleButton').click();ok('保存503保留未保存表单与旧规则');
await select(p,'日本橋');state.current.rules[0].revision++;state.current.rules[0].reading='ニホンバシ';state.current.version++;await p.locator('#readingInput').fill('にっぽんばし');await p.locator('#saveRuleButton').click();await p.locator('#saveError').waitFor();assert.match(await p.locator('#saveError').innerText(),/另一窗口/);await p.locator('#cancelRuleButton').click();await p.waitForFunction(()=>document.querySelector('#articleEditor mark').title.includes('ニホンバシ'));ok('409冲突不覆盖，刷新后可重新编辑');
state.voices=true;await p.locator('#retryVoices').click();await p.waitForFunction(()=>!document.querySelector('#generateButton').disabled);await select(p,'日本橋');await p.locator('#readingInput').fill('にっぽんばし');const version=state.current.version;await p.locator('#previewReading').click();await p.waitForFunction(()=>!document.querySelector('#previewReading').disabled);assert.equal(state.current.version,version);const preview=state.requests.filter(r=>r.path.endsWith('/preview')).at(-1);assert.equal(preview.body.reading,'にっぽんばし');await p.locator('#cancelRuleButton').click();ok('草稿试听独立API且不保存个人规则');
await p.locator('#generateButton').click();await p.locator('#audioResult').waitFor();const speech=state.requests.filter(r=>r.path.endsWith('/speech')).at(-1);assert(speech.body.input.includes('日本橋'));assert(!speech.body.input.includes('ニホンバシ'));await p.locator('#playButton').click();await p.waitForFunction(()=>document.querySelector('#playState').textContent==='正在播放');await p.locator('#playButton').click();await p.waitForFunction(()=>['已暂停','已停止'].includes(document.querySelector('#playState').textContent));await p.locator('#playButton').click();await p.locator('#stopButton').click();const download=await Promise.all([p.waitForEvent('download'),p.locator('#downloadButton').click()]);assert.equal(download[0].suggestedFilename(),'contract-test.mp3');assert.equal(fs.statSync(await download[0].path()).size,audio.length);ok('原文合成请求、真实MP3 Blob播放暂停停止与下载');
await select(p,'日本橋');await save(p,'にっぽんばし');assert(await p.locator('#staleBanner').isVisible());state.audioFail=true;const before=state.requests.filter(r=>r.path.endsWith('/speech')).length;await p.locator('#generateButton').click();await p.locator('#generationError').waitFor();assert(await p.locator('#staleBanner').isVisible());assert.equal(state.requests.filter(r=>r.path.endsWith('/speech')).length,before+1);state.audioFail=false;state.badAudio=true;await p.locator('#generateButton').click();await p.waitForFunction(()=>document.querySelector('#generationError').textContent.includes('格式'));assert(await p.locator('#staleBanner').isVisible());state.badAudio=false;await p.locator('#generateButton').click();await p.waitForFunction(()=>document.querySelector('#staleBanner').hidden);ok('旧音频标记、503/错误MIME保留旧结果且不自动重试');
state.delayAudio=350;await p.locator('#generateButton').click();await p.locator('#speedRange').fill('1.5');await p.waitForFunction(()=>!document.querySelector('#generateButton').disabled);assert(await p.locator('#staleBanner').isVisible());state.delayAudio=0;ok('在途音频绑定原提交参数和实际规则版本');
await p.locator('[data-view="rules"]').click();await p.locator('#addRuleButton').click();await p.locator('#modalWord').fill('京都');await p.locator('#modalReading').fill('きょうと');await p.locator('#modalSave').click();await p.locator('#ruleDialog').waitFor({state:'hidden'});await p.locator('#ruleSearch').fill('不存在');assert(await p.locator('#rulesEmpty').isVisible());await p.locator('#ruleSearch').fill('');await p.locator('[aria-label="删除 京都"]').click();state.fail='DELETE:/v1/vocabulary/'+state.current.rules.find(r=>r.text==='京都').id;await p.locator('#confirmDelete').click();await p.locator('#deleteError').waitFor();assert(state.current.rules.some(r=>r.text==='京都'));await p.locator('#confirmDelete').click();await p.locator('#confirmDialog').waitFor({state:'hidden'});assert(!state.current.rules.some(r=>r.text==='京都'));ok('规则独立新增查询、删除失败保持及204版本更新');
// More than one UI page must not truncate full-body rule projection.
for(let i=0;i<24;i++)state.current.rules.push({id:randomUUID(),text:'単語'+i,reading:'たんご',revision:1,createdAt:new Date().toISOString(),updatedAt:new Date().toISOString()});state.current.version++;await p.reload();await p.locator('#rulesTableBody tr').first().waitFor();assert.equal(await p.locator('#rulesTableBody tr').count(),20);await p.getByRole('button',{name:'下一页'}).click();assert.equal(await p.locator('#rulesTableBody tr').count(),5);await openWorkbench(p);await p.locator('#articleEditor').fill('単語23\n日本橋😀\n\nカタカナとひらがな。');assert.equal(await p.locator('#articleEditor mark').count(),2);assert.equal(await p.locator('#articleEditor').textContent(),'単語23\n日本橋😀\n\nカタカナとひらがな。');await p.locator('#articleEditor').press('Control+End');await p.locator('#articleEditor').press('Enter');await p.locator('#articleEditor').pressSequentially('日本橋');assert((await p.locator('#articleEditor').textContent()).endsWith('\n日本橋'));ok('列表分页与完整投影，多行emoji及连续输入');
await p.locator('#articleEditor').evaluate(e=>{e.dispatchEvent(new CompositionEvent('compositionstart',{bubbles:true}));e.textContent='変換中の日本橋';e.dispatchEvent(new InputEvent('input',{bubbles:true,isComposing:true,data:'橋'}));});assert.equal(await p.locator('#articleEditor mark').count(),0);await p.locator('#articleEditor').evaluate(e=>e.dispatchEvent(new CompositionEvent('compositionend',{bubbles:true,data:'橋'})));await p.waitForFunction(()=>document.querySelectorAll('#articleEditor mark').length===1);ok('React IME合成期间不重写，提交后重算');
await p.locator('#articleEditor').fill('日'.repeat(10001));assert(await p.locator('#generateButton').isDisabled());await p.locator('#articleEditor').fill('');assert(await p.locator('#generateButton').isDisabled());await createArticle(p,'京都的早晨','京都の朝。日本橋を歩く。日本橋の空。');ok('长文和空正文禁用');
await p.locator('[data-view="account"]').click();await p.locator('#displayName').fill('林の書斎');await p.locator('#profileSave').click();await p.waitForFunction(()=>document.querySelector('#profileName').textContent==='林の書斎');ok('账户资料PATCH契约');
for(const width of [1440,390,320]){await p.setViewportSize({width,height:width===1440?1000:844});for(const view of ['workbench','rules','account']){await p.locator(`[data-view="${view}"]`).click();await p.locator(`#${view}View`).waitFor();assert(await p.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1),view+width);await screenshot(p,view+'-'+width);}}
await p.locator('[data-view="workbench"]').click();await select(p,'日本橋');await screenshot(p,'reading-320');for(let i=0;i<12;i++){await p.keyboard.press('Tab');assert(await p.evaluate(()=>!!document.activeElement.closest('[role="dialog"]')));}await p.keyboard.press('Escape');assert.equal(await p.locator('#readingDialog').count(),0);ok('1440/390/320布局、Radix焦点约束与Escape');
state.current=null;await select(p,'日本橋');await p.locator('#readingInput').fill('にほんばし');await p.locator('#saveRuleButton').click();await p.locator('#authView').waitFor();assert.match(await p.locator('#sessionNotice').innerText(),/失效/);await login(p);assert((await p.locator('#articleEditor').textContent()).includes('日本橋'));ok('真实401会话失效、原文保留和重新登录');
await p.locator('[data-view="account"]').click();await p.locator('#logoutButton').click();await p.locator('#authView').waitFor();const reads=state.csrfReads;await register(p,'second');await login(p,'second');assert.equal(await p.locator('#navRuleCount').textContent(),'0');assert.equal(await p.locator('#articleEditor').textContent(),'');assert(state.csrfReads>=reads);ok('退出CSRF轮换、另一账户数据隔离');
await p.locator('[data-view="account"]').click();await p.locator('#logoutButton').click();state.registration=false;await p.goto(base+'#/register');await p.reload();await p.waitForFunction(()=>document.querySelector('#authTitle')?.textContent.includes('暂未开放'));assert.equal(await p.locator('#authForm').count(),0);ok('注册关闭与直达路由');
assert.equal(await p.evaluate(()=>localStorage.length),0);assert.deepEqual(errors,[]);ok('正式React不写本机账户规则，无页面异常');
fs.writeFileSync(path.join(out,'results.json'),JSON.stringify({date:new Date().toISOString(),contract:contractMetadata.version,sha256:contractMetadata.sha256,checks,errors,note:'HTTP contract test doubles only; real MP3 tone fixture, not Japanese provider acceptance'},null,2));
}finally{await browser.close();}})().catch(e=>{console.error(e);process.exit(1)});
